name: Node.js Update

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Autoupdater for dependencies (Node JS)
        uses: siarheidudko/autoupdater@v3
            
